### ISSUE TITLE
Are the baseline results wrong?

### ISSUE THREAD

**Issue by harveenchadha** [Speech-Lab-IITM/English_ASR_Challenge#2]
Hi,

I have a doubt, The baseline results mentioned here are 

| Model | WER            |
|------------------|-------------------|
| dev_IITM | 6.65                |
| dev_NPTEL  | 13.08               |

After training a number of models, none of the results are inline with the baseline scores. 

I think the WER numbers might have got interchanged and the actual numbers might be:

| Model | WER            |
|------------------|-------------------|
| dev_IITM | 13.08                 |
| dev_NPTEL  |      6.65         |

Can you please check and reconfirm?

**Comment by harveenchadha** [comment]
The sets were correct!

**Comment by yunxinmengze** [comment]
@harveenchadha 

The data download channel has been closed. Can you share the downloaded data.
thank you very mush.
